[package]
name = "tetris"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = { version = "0.8.5", features = [] }
leptos = { version = "0.5.4", features = ["csr"] }
wasm-bindgen = "0.2.89"
